// Sports offered when starting a research run.
export const SPORT_OPTIONS = [
  { value: "baseball", label: "Baseball" },
  { value: "basketball", label: "Basketball" },
  { value: "bodybuilding", label: "Bodybuilding" },
  { value: "boxing", label: "Boxing" },
  { value: "cheerleading", label: "Cheerleading" },
  { value: "climbing", label: "Climbing" },
  { value: "crossfit", label: "CrossFit" },
  { value: "cycling", label: "Cycling" },
  { value: "dance", label: "Dance" },
  { value: "diving", label: "Diving" },
  { value: "equestrian", label: "Equestrian" },
  { value: "esports", label: "Esports" },
  { value: "figure-skating", label: "Figure Skating" },
  { value: "fitness", label: "Fitness" },
  { value: "football", label: "Football (American)" },
  { value: "golf", label: "Golf" },
  { value: "gymnastics", label: "Gymnastics" },
  { value: "hockey", label: "Hockey" },
  { value: "lacrosse", label: "Lacrosse" },
  { value: "martial-arts", label: "Martial Arts" },
  { value: "mma", label: "MMA / UFC" },
  { value: "motocross", label: "Motocross" },
  { value: "motorcycle racing", label: "Motorcycle Racing" },
  { value: "motorsports", label: "Motorsports" },
  { value: "olympic", label: "Olympic Sports" },
  { value: "pickleball", label: "Pickleball" },
  { value: "pilates", label: "Pilates" },
  { value: "pole-fitness", label: "Pole Fitness" },
  { value: "powerlifting", label: "Powerlifting" },
  { value: "rugby", label: "Rugby" },
  { value: "running", label: "Running / Track" },
  { value: "skateboarding", label: "Skateboarding" },
  { value: "skiing", label: "Skiing" },
  { value: "snowboarding", label: "Snowboarding" },
  { value: "soccer", label: "Soccer" },
  { value: "softball", label: "Softball" },
  { value: "surfing", label: "Surfing" },
  { value: "swimming", label: "Swimming" },
  { value: "tennis", label: "Tennis" },
  { value: "triathlon", label: "Triathlon" },
  { value: "volleyball", label: "Volleyball" },
  { value: "wakeboarding", label: "Wakeboarding" },
  { value: "weightlifting", label: "Weightlifting" },
  { value: "wrestling", label: "Wrestling" },
  { value: "yoga", label: "Yoga" },
];
